// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: WidevinePsshData.proto 
// Input based on: https://github.com/google/shaka-packager/blob/master/packager/media/base/widevine_pssh_data.proto
//
// Licensing text of the base proto file: 
// ======================================================
// Copyright 2016 Google Inc. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd
// ======================================================


#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace shaka.media
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WidevinePsshData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(Algorithm.Unencrypted)]
        public Algorithm algorithm
        {
            get { return __pbn__algorithm ?? Algorithm.Unencrypted; }
            set { __pbn__algorithm = value; }
        }
        public bool ShouldSerializealgorithm() => __pbn__algorithm != null;
        public void Resetalgorithm() => __pbn__algorithm = null;
        private Algorithm? __pbn__algorithm;

        [global::ProtoBuf.ProtoMember(2, Name = @"key_id")]
        public global::System.Collections.Generic.List<byte[]> KeyIds { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(3, Name = @"provider")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Provider
        {
            get { return __pbn__Provider ?? ""; }
            set { __pbn__Provider = value; }
        }
        public bool ShouldSerializeProvider() => __pbn__Provider != null;
        public void ResetProvider() => __pbn__Provider = null;
        private string __pbn__Provider;

        [global::ProtoBuf.ProtoMember(4, Name = @"content_id")]
        public byte[] ContentId
        {
            get { return __pbn__ContentId; }
            set { __pbn__ContentId = value; }
        }
        public bool ShouldSerializeContentId() => __pbn__ContentId != null;
        public void ResetContentId() => __pbn__ContentId = null;
        private byte[] __pbn__ContentId;

        [global::ProtoBuf.ProtoMember(6, Name = @"policy")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Policy
        {
            get { return __pbn__Policy ?? ""; }
            set { __pbn__Policy = value; }
        }
        public bool ShouldSerializePolicy() => __pbn__Policy != null;
        public void ResetPolicy() => __pbn__Policy = null;
        private string __pbn__Policy;

        [global::ProtoBuf.ProtoMember(7, Name = @"crypto_period_index")]
        public uint CryptoPeriodIndex
        {
            get { return __pbn__CryptoPeriodIndex.GetValueOrDefault(); }
            set { __pbn__CryptoPeriodIndex = value; }
        }
        public bool ShouldSerializeCryptoPeriodIndex() => __pbn__CryptoPeriodIndex != null;
        public void ResetCryptoPeriodIndex() => __pbn__CryptoPeriodIndex = null;
        private uint? __pbn__CryptoPeriodIndex;

        [global::ProtoBuf.ProtoMember(8, Name = @"grouped_license")]
        public byte[] GroupedLicense
        {
            get { return __pbn__GroupedLicense; }
            set { __pbn__GroupedLicense = value; }
        }
        public bool ShouldSerializeGroupedLicense() => __pbn__GroupedLicense != null;
        public void ResetGroupedLicense() => __pbn__GroupedLicense = null;
        private byte[] __pbn__GroupedLicense;

        [global::ProtoBuf.ProtoMember(9, Name = @"protection_scheme")]
        public uint ProtectionScheme
        {
            get { return __pbn__ProtectionScheme.GetValueOrDefault(); }
            set { __pbn__ProtectionScheme = value; }
        }
        public bool ShouldSerializeProtectionScheme() => __pbn__ProtectionScheme != null;
        public void ResetProtectionScheme() => __pbn__ProtectionScheme = null;
        private uint? __pbn__ProtectionScheme;

        [global::ProtoBuf.ProtoContract()]
        public enum Algorithm
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNENCRYPTED")]
            Unencrypted = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"AESCTR")]
            Aesctr = 1,
        }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
